// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_ParaEnvia.h"
#include "ui_TelaNotificacoes.h"
#include "ui_ScreenSleepMode.h"
#include "ui_Estoque.h"
#include "ui_MercadoLivre.h"
#include "ui_Compras.h"
#include "ui_Lucro.h"
#include "ui_Shopee.h"
#include "ui_TelaParaEnviar.h"
#include "ui_TelaParaRetirada.h"
#include "ui_TelaParaImprimir.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_1275313820);    // assets/click (2).png
LV_IMG_DECLARE(ui_img_package_png);    // assets/package.png
LV_IMG_DECLARE(ui_img_click_png);    // assets/click.png
LV_IMG_DECLARE(ui_img_201442241);    // assets/in-stock.png
LV_IMG_DECLARE(ui_img_handshake_png);    // assets/handshake.png
LV_IMG_DECLARE(ui_img_cart_png);    // assets/cart.png
LV_IMG_DECLARE(ui_img_profit_png);    // assets/profit.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/delete.png
LV_IMG_DECLARE(ui_img_1973681197);    // assets/dark-mode.png
LV_IMG_DECLARE(ui_img_8670999);    // assets/wi-fi (3).png
LV_IMG_DECLARE(ui_img_wifi_4_png);    // assets/wifi 4.png
LV_IMG_DECLARE(ui_img_462869052);    // assets/notification (1).png
LV_IMG_DECLARE(ui_img_return_png);    // assets/return.png
LV_IMG_DECLARE(ui_img_1275314971);    // assets/click (1).png
LV_IMG_DECLARE(ui_img_659251599);    // assets/printer (1).png
LV_IMG_DECLARE(ui_img_747636525);    // assets/press-button.png
LV_IMG_DECLARE(ui_img_725899859);    // assets/box (2).png
LV_IMG_DECLARE(ui_img_box_png);    // assets/box.png
LV_IMG_DECLARE(ui_img_wdaswdasdaw_png);    // assets/wdaswdasdaw.png
LV_IMG_DECLARE(ui_img_close_png);    // assets/close.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
