// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COMPRAS_H
#define UI_COMPRAS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Compras
extern void ui_Compras_screen_init(void);
extern void ui_Compras_screen_destroy(void);
extern lv_obj_t * ui_Compras;
extern lv_obj_t * ui_RETURNHOME7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

