// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_SwitchTheme_SwitchTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_SwitchTheme = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_BLACK);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_LIGHT);
    }
}

// COMPONENT SwitchTheme

lv_obj_t * ui_SwitchTheme_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SwitchTheme;
    cui_SwitchTheme = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_SwitchTheme, 50);
    lv_obj_set_height(cui_SwitchTheme, 25);
    lv_obj_set_x(cui_SwitchTheme, 128);
    lv_obj_set_y(cui_SwitchTheme, -101);
    lv_obj_set_align(cui_SwitchTheme, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_SwitchTheme, lv_color_hex(0xFFF800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_SwitchTheme, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0xECE916), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0xFFF800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_SwitchTheme, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0xFFF800), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(cui_SwitchTheme, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_SwitchTheme, LV_GRAD_DIR_NONE, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_SwitchTheme, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_SwitchTheme, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCHTHEME_NUM);
    children[UI_COMP_SWITCHTHEME_SWITCHTHEME] = cui_SwitchTheme;
    lv_obj_add_event_cb(cui_SwitchTheme, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SwitchTheme, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_SwitchTheme, ui_event_comp_SwitchTheme_SwitchTheme, LV_EVENT_ALL, children);
    ui_comp_SwitchTheme_create_hook(cui_SwitchTheme);
    return cui_SwitchTheme;
}

