// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_RETURNHOME_RETURNHOME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_RETURNHOME = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// COMPONENT RETURNHOME

lv_obj_t * ui_RETURNHOME_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_RETURNHOME;
    cui_RETURNHOME = lv_imgbtn_create(comp_parent);
    lv_imgbtn_set_src(cui_RETURNHOME, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_return_png, NULL);
    lv_obj_set_width(cui_RETURNHOME, 32);
    lv_obj_set_height(cui_RETURNHOME, 32);
    lv_obj_set_x(cui_RETURNHOME, -139);
    lv_obj_set_y(cui_RETURNHOME, -99);
    lv_obj_set_align(cui_RETURNHOME, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_RETURNHOME, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_RETURNHOME_NUM);
    children[UI_COMP_RETURNHOME_RETURNHOME] = cui_RETURNHOME;
    lv_obj_add_event_cb(cui_RETURNHOME, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_RETURNHOME, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_RETURNHOME, ui_event_comp_RETURNHOME_RETURNHOME, LV_EVENT_ALL, children);
    ui_comp_RETURNHOME_create_hook(cui_RETURNHOME);
    return cui_RETURNHOME;
}

