// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Compras = NULL;
lv_obj_t * ui_RETURNHOME7 = NULL;
// event funtions

// build funtions

void ui_Compras_screen_init(void)
{
    ui_Compras = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Compras, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Compras, lv_color_hex(0xF15252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Compras, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME7 = ui_RETURNHOME_create(ui_Compras);
    lv_obj_set_x(ui_RETURNHOME7, -139);
    lv_obj_set_y(ui_RETURNHOME7, -99);

}

void ui_Compras_screen_destroy(void)
{
    if(ui_Compras) lv_obj_del(ui_Compras);

    // NULL screen variables
    ui_Compras = NULL;
    ui_RETURNHOME7 = NULL;

}
