// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT BotaoSelecao

lv_obj_t * ui_BotaoSelecao_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BotaoSelecao;
    cui_BotaoSelecao = lv_imgbtn_create(comp_parent);
    lv_imgbtn_set_src(cui_BotaoSelecao, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_659251599, NULL);
    lv_imgbtn_set_src(cui_BotaoSelecao, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_747636525, NULL);
    lv_obj_set_width(cui_BotaoSelecao, 128);
    lv_obj_set_height(cui_BotaoSelecao, 128);
    lv_obj_set_x(cui_BotaoSelecao, -24);
    lv_obj_set_y(cui_BotaoSelecao, -27);
    lv_obj_set_align(cui_BotaoSelecao, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BOTAOSELECAO_NUM);
    children[UI_COMP_BOTAOSELECAO_BOTAOSELECAO] = cui_BotaoSelecao;
    lv_obj_add_event_cb(cui_BotaoSelecao, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BotaoSelecao, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BotaoSelecao_create_hook(cui_BotaoSelecao);
    return cui_BotaoSelecao;
}

