// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SWITCHTHEME_H
#define _UI_COMP_SWITCHTHEME_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SwitchTheme
#define UI_COMP_SWITCHTHEME_SWITCHTHEME 0
#define _UI_COMP_SWITCHTHEME_NUM 1
lv_obj_t * ui_SwitchTheme_create(lv_obj_t * comp_parent);
void ui_event_comp_SwitchTheme_SwitchTheme(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
