// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ESTOQUE_H
#define UI_ESTOQUE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Estoque
extern void ui_Estoque_screen_init(void);
extern void ui_Estoque_screen_destroy(void);
extern lv_obj_t * ui_Estoque;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_LabelStockCP1;
extern lv_obj_t * ui_LabelStockCP2;
extern lv_obj_t * ui_RETURNHOME5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

