// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Estoque = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_LabelStockCP1 = NULL;
lv_obj_t * ui_LabelStockCP2 = NULL;
lv_obj_t * ui_RETURNHOME5 = NULL;
// event funtions

// build funtions

void ui_Estoque_screen_init(void)
{
    ui_Estoque = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Estoque, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Estoque, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Estoque, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Estoque);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -82);
    lv_obj_set_y(ui_Label21, -59);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Product 1");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Estoque);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -80);
    lv_obj_set_y(ui_Label22, -35);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Product 2");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStockCP1 = lv_label_create(ui_Estoque);
    lv_obj_set_width(ui_LabelStockCP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStockCP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStockCP1, 6);
    lv_obj_set_y(ui_LabelStockCP1, -59);
    lv_obj_set_align(ui_LabelStockCP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStockCP1, "--");
    lv_obj_set_style_text_color(ui_LabelStockCP1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStockCP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStockCP2 = lv_label_create(ui_Estoque);
    lv_obj_set_width(ui_LabelStockCP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStockCP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStockCP2, 7);
    lv_obj_set_y(ui_LabelStockCP2, -34);
    lv_obj_set_align(ui_LabelStockCP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStockCP2, "--");
    lv_obj_set_style_text_color(ui_LabelStockCP2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStockCP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME5 = ui_RETURNHOME_create(ui_Estoque);
    lv_obj_set_x(ui_RETURNHOME5, -139);
    lv_obj_set_y(ui_RETURNHOME5, -99);

}

void ui_Estoque_screen_destroy(void)
{
    if(ui_Estoque) lv_obj_del(ui_Estoque);

    // NULL screen variables
    ui_Estoque = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_LabelStockCP1 = NULL;
    ui_LabelStockCP2 = NULL;
    ui_RETURNHOME5 = NULL;

}
