// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LUCRO_H
#define UI_LUCRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Lucro
extern void ui_Lucro_screen_init(void);
extern void ui_Lucro_screen_destroy(void);
extern lv_obj_t * ui_Lucro;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_LabelProfitMonth;
extern lv_obj_t * ui_LabelProfit30d;
extern lv_obj_t * ui_LabelProfit7d;
extern lv_obj_t * ui_LabelProfitToday;
extern lv_obj_t * ui_RETURNHOME8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

