// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Lucro = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_LabelProfitMonth = NULL;
lv_obj_t * ui_LabelProfit30d = NULL;
lv_obj_t * ui_LabelProfit7d = NULL;
lv_obj_t * ui_LabelProfitToday = NULL;
lv_obj_t * ui_RETURNHOME8 = NULL;
// event funtions

// build funtions

void ui_Lucro_screen_init(void)
{
    ui_Lucro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Lucro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lucro, lv_color_hex(0x36AF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lucro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -82);
    lv_obj_set_y(ui_Label13, -101);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Profit Of The Last:");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -122);
    lv_obj_set_y(ui_Label14, -79);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Hoje");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -120);
    lv_obj_set_y(ui_Label15, -41);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "30 Dias:");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -122);
    lv_obj_set_y(ui_Label17, -60);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "7 Dias:");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -120);
    lv_obj_set_y(ui_Label18, -22);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Este Mes:");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProfitMonth = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_LabelProfitMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProfitMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProfitMonth, -71);
    lv_obj_set_y(ui_LabelProfitMonth, -23);
    lv_obj_set_align(ui_LabelProfitMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProfitMonth, "--");
    lv_obj_set_style_text_color(ui_LabelProfitMonth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProfitMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProfit30d = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_LabelProfit30d, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProfit30d, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProfit30d, -75);
    lv_obj_set_y(ui_LabelProfit30d, -42);
    lv_obj_set_align(ui_LabelProfit30d, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProfit30d, "--");
    lv_obj_set_style_text_color(ui_LabelProfit30d, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProfit30d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProfit7d = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_LabelProfit7d, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProfit7d, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProfit7d, -77);
    lv_obj_set_y(ui_LabelProfit7d, -61);
    lv_obj_set_align(ui_LabelProfit7d, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProfit7d, "--");
    lv_obj_set_style_text_color(ui_LabelProfit7d, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProfit7d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProfitToday = lv_label_create(ui_Lucro);
    lv_obj_set_width(ui_LabelProfitToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProfitToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProfitToday, -79);
    lv_obj_set_y(ui_LabelProfitToday, -78);
    lv_obj_set_align(ui_LabelProfitToday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProfitToday, "--");
    lv_obj_set_style_text_color(ui_LabelProfitToday, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProfitToday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME8 = ui_RETURNHOME_create(ui_Lucro);
    lv_obj_set_x(ui_RETURNHOME8, 137);
    lv_obj_set_y(ui_RETURNHOME8, -98);

}

void ui_Lucro_screen_destroy(void)
{
    if(ui_Lucro) lv_obj_del(ui_Lucro);

    // NULL screen variables
    ui_Lucro = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_LabelProfitMonth = NULL;
    ui_LabelProfit30d = NULL;
    ui_LabelProfit7d = NULL;
    ui_LabelProfitToday = NULL;
    ui_RETURNHOME8 = NULL;

}
