// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MercadoLivre = NULL;
lv_obj_t * ui_LabelSalesML = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_RETURNHOME6 = NULL;
// event funtions

// build funtions

void ui_MercadoLivre_screen_init(void)
{
    ui_MercadoLivre = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MercadoLivre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MercadoLivre, lv_color_hex(0xFFDB00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MercadoLivre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSalesML = lv_label_create(ui_MercadoLivre);
    lv_obj_set_width(ui_LabelSalesML, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalesML, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSalesML, -6);
    lv_obj_set_y(ui_LabelSalesML, -81);
    lv_obj_set_align(ui_LabelSalesML, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalesML, "--");

    ui_Label20 = lv_label_create(ui_MercadoLivre);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -2);
    lv_obj_set_y(ui_Label20, -105);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Mercado Livre Sell's");

    ui_RETURNHOME6 = ui_RETURNHOME_create(ui_MercadoLivre);
    lv_obj_set_x(ui_RETURNHOME6, -139);
    lv_obj_set_y(ui_RETURNHOME6, -99);

}

void ui_MercadoLivre_screen_destroy(void)
{
    if(ui_MercadoLivre) lv_obj_del(ui_MercadoLivre);

    // NULL screen variables
    ui_MercadoLivre = NULL;
    ui_LabelSalesML = NULL;
    ui_Label20 = NULL;
    ui_RETURNHOME6 = NULL;

}
