// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MERCADOLIVRE_H
#define UI_MERCADOLIVRE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MercadoLivre
extern void ui_MercadoLivre_screen_init(void);
extern void ui_MercadoLivre_screen_destroy(void);
extern lv_obj_t * ui_MercadoLivre;
extern lv_obj_t * ui_LabelSalesML;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_RETURNHOME6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

