// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PARAENVIA_H
#define UI_PARAENVIA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParaEnvia
extern void ui_ParaEnvia_screen_init(void);
extern void ui_ParaEnvia_screen_destroy(void);
extern lv_obj_t * ui_ParaEnvia;
extern lv_obj_t * ui_RETURNHOME;
extern lv_obj_t * ui_Panel3;
extern void ui_event_BotaoSelecao_BotaoSelecao(lv_event_t * e);
extern lv_obj_t * ui_BotaoSelecao;
extern void ui_event_BotaoSelecao1_BotaoSelecao(lv_event_t * e);
extern lv_obj_t * ui_BotaoSelecao1;
extern void ui_event_BotaoSelecao2_BotaoSelecao(lv_event_t * e);
extern lv_obj_t * ui_BotaoSelecao2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

