// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ParaEnvia = NULL;
lv_obj_t * ui_RETURNHOME = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_BotaoSelecao = NULL;
lv_obj_t * ui_BotaoSelecao1 = NULL;
lv_obj_t * ui_BotaoSelecao2 = NULL;
// event funtions
void ui_event_BotaoSelecao_BotaoSelecao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TelaParaImprimir, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TelaParaImprimir_screen_init);
    }
}

void ui_event_BotaoSelecao1_BotaoSelecao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TelaParaEnviar, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TelaParaEnviar_screen_init);
    }
}

void ui_event_BotaoSelecao2_BotaoSelecao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TelaParaRetirada, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TelaParaRetirada_screen_init);
    }
}

// build funtions

void ui_ParaEnvia_screen_init(void)
{
    ui_ParaEnvia = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ParaEnvia, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_flex_flow(ui_ParaEnvia, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ParaEnvia, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ParaEnvia, lv_color_hex(0x5F5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParaEnvia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ParaEnvia, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ParaEnvia, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParaEnvia, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ParaEnvia, lv_color_hex(0x4E4E4E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ParaEnvia, LV_GRAD_DIR_HOR, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RETURNHOME = ui_RETURNHOME_create(ui_ParaEnvia);
    lv_imgbtn_set_src(ui_RETURNHOME, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1275314971, NULL);
    lv_obj_set_x(ui_RETURNHOME, -139);
    lv_obj_set_y(ui_RETURNHOME, -99);

    ui_Panel3 = lv_obj_create(ui_ParaEnvia);
    lv_obj_set_width(ui_Panel3, 320);
    lv_obj_set_height(ui_Panel3, 155);
    lv_obj_set_x(ui_Panel3, 225);
    lv_obj_set_y(ui_Panel3, -13);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_Panel3, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotaoSelecao = ui_BotaoSelecao_create(ui_Panel3);
    lv_obj_set_x(ui_BotaoSelecao, -24);
    lv_obj_set_y(ui_BotaoSelecao, -27);

    ui_BotaoSelecao1 = ui_BotaoSelecao_create(ui_Panel3);
    lv_imgbtn_set_src(ui_BotaoSelecao1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_725899859, NULL);
    lv_obj_set_x(ui_BotaoSelecao1, -24);
    lv_obj_set_y(ui_BotaoSelecao1, -27);

    ui_BotaoSelecao2 = ui_BotaoSelecao_create(ui_Panel3);
    lv_imgbtn_set_src(ui_BotaoSelecao2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_box_png, NULL);
    lv_obj_set_x(ui_BotaoSelecao2, -24);
    lv_obj_set_y(ui_BotaoSelecao2, -27);

    lv_obj_add_event_cb(ui_BotaoSelecao, ui_event_BotaoSelecao_BotaoSelecao, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotaoSelecao1, ui_event_BotaoSelecao1_BotaoSelecao, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotaoSelecao2, ui_event_BotaoSelecao2_BotaoSelecao, LV_EVENT_ALL, NULL);

}

void ui_ParaEnvia_screen_destroy(void)
{
    if(ui_ParaEnvia) lv_obj_del(ui_ParaEnvia);

    // NULL screen variables
    ui_ParaEnvia = NULL;
    ui_RETURNHOME = NULL;
    ui_Panel3 = NULL;
    ui_BotaoSelecao = NULL;
    ui_BotaoSelecao1 = NULL;
    ui_BotaoSelecao2 = NULL;

}
