// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label4;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label6;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label7;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label8;
extern void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label9;
extern void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label10;
extern void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_SwitchTheme1;
extern lv_obj_t * ui_Tablea1;
extern void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
extern void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
extern void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
extern void ui_event_ImgButton14(lv_event_t * e);
extern lv_obj_t * ui_ImgButton14;
extern void ui_event_ScreenSleepMode1(lv_event_t * e);
extern lv_obj_t * ui_ScreenSleepMode1;
extern lv_obj_t * ui_LabelClock;
extern lv_obj_t * ui_SliderWifi;
extern lv_obj_t * ui_Notificacoes;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_NotificationNumber;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

