// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Switch6 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_SwitchTheme1 = NULL;
lv_obj_t * ui_Tablea1 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_ImgButton10 = NULL;
lv_obj_t * ui_ImgButton11 = NULL;
lv_obj_t * ui_ImgButton12 = NULL;
lv_obj_t * ui_ImgButton13 = NULL;
lv_obj_t * ui_ImgButton14 = NULL;
lv_obj_t * ui_ScreenSleepMode1 = NULL;
lv_obj_t * ui_LabelClock = NULL;
lv_obj_t * ui_SliderWifi = NULL;
lv_obj_t * ui_Notificacoes = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_NotificationNumber = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ScreenSleepMode1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Notificacoes, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_SliderWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Tablea1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Tablea1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_SliderWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Notificacoes, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ScreenSleepMode1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton11, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton12, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Switch6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImgButton14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ParaEnvia, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ParaEnvia_screen_init);
    }
}

void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Estoque, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Estoque_screen_init);
    }
}

void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MercadoLivre, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MercadoLivre_screen_init);
    }
}

void ui_event_ImgButton12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Compras, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Compras_screen_init);
    }
}

void ui_event_ImgButton13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Lucro, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Lucro_screen_init);
    }
}

void ui_event_ImgButton14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Shopee, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Shopee_screen_init);
    }
}

void ui_event_ScreenSleepMode1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSleepMode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSleepMode_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TelaNotificacoes, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TelaNotificacoes_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x5F5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_White);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Screen1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x4E4E4E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_HOR, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setting_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1275313820, NULL);
    lv_obj_set_width(ui_ImgButton1, 24);
    lv_obj_set_height(ui_ImgButton1, 24);
    lv_obj_set_x(ui_ImgButton1, -146);
    lv_obj_set_y(ui_ImgButton1, -105);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 163);
    lv_obj_set_height(ui_Panel2, 242);
    lv_obj_set_x(ui_Panel2, 78);
    lv_obj_set_y(ui_Panel2, -2);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button3, 163);
    lv_obj_set_height(ui_Button3, 242);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 158);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_x(ui_Panel1, -83);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x818181), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, -6);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "Settings");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_Label1, 0, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Panel8 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel8, 140);
    lv_obj_set_height(ui_Panel8, 24);
    lv_obj_set_x(ui_Panel8, -91);
    lv_obj_set_y(ui_Panel8, -68);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -41);
    lv_obj_set_y(ui_Label4, -2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Send");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch1, 40);
    lv_obj_set_height(ui_Switch1, 18);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Panel9 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel9, 140);
    lv_obj_set_height(ui_Panel9, 24);
    lv_obj_set_x(ui_Panel9, -91);
    lv_obj_set_y(ui_Panel9, -68);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -41);
    lv_obj_set_y(ui_Label6, -2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Stock");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch2, 40);
    lv_obj_set_height(ui_Switch2, 18);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Panel10 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel10, 140);
    lv_obj_set_height(ui_Panel10, 24);
    lv_obj_set_x(ui_Panel10, -91);
    lv_obj_set_y(ui_Panel10, -68);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -41);
    lv_obj_set_y(ui_Label7, -2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "ML");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Panel10);
    lv_obj_set_width(ui_Switch3, 40);
    lv_obj_set_height(ui_Switch3, 18);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_Panel11 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel11, 140);
    lv_obj_set_height(ui_Panel11, 24);
    lv_obj_set_x(ui_Panel11, -91);
    lv_obj_set_y(ui_Panel11, -68);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -41);
    lv_obj_set_y(ui_Label8, -2);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Boughts");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Panel11);
    lv_obj_set_width(ui_Switch4, 40);
    lv_obj_set_height(ui_Switch4, 18);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    ui_Panel12 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel12, 140);
    lv_obj_set_height(ui_Panel12, 24);
    lv_obj_set_x(ui_Panel12, -91);
    lv_obj_set_y(ui_Panel12, -68);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -41);
    lv_obj_set_y(ui_Label9, -2);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Profit");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Panel12);
    lv_obj_set_width(ui_Switch5, 40);
    lv_obj_set_height(ui_Switch5, 18);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);

    ui_Panel13 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel13, 140);
    lv_obj_set_height(ui_Panel13, 24);
    lv_obj_set_x(ui_Panel13, -91);
    lv_obj_set_y(ui_Panel13, -68);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -41);
    lv_obj_set_y(ui_Label10, -2);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Shopee");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_Panel13);
    lv_obj_set_width(ui_Switch6, 40);
    lv_obj_set_height(ui_Switch6, 18);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);

    ui_Panel14 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel14, 140);
    lv_obj_set_height(ui_Panel14, 24);
    lv_obj_set_x(ui_Panel14, -91);
    lv_obj_set_y(ui_Panel14, -68);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -41);
    lv_obj_set_y(ui_Label11, -2);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Theme:");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchTheme1 = ui_SwitchTheme_create(ui_Panel14);
    lv_obj_set_width(ui_SwitchTheme1, 50);
    lv_obj_set_height(ui_SwitchTheme1, 16);
    lv_obj_set_x(ui_SwitchTheme1, 37);
    lv_obj_set_y(ui_SwitchTheme1, 0);
    lv_obj_clear_flag(ui_SwitchTheme1, LV_OBJ_FLAG_IGNORE_LAYOUT);      /// Flags

    ui_Tablea1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Tablea1, 320);
    lv_obj_set_height(ui_Tablea1, 145);
    lv_obj_set_x(ui_Tablea1, -1);
    lv_obj_set_y(ui_Tablea1, -3);
    lv_obj_set_align(ui_Tablea1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Tablea1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Tablea1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tablea1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Tablea1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Tablea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Tablea1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tablea1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Tablea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Tablea1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Tablea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Tablea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Tablea1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tablea1, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImgButton9 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_package_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton9, 64);
    lv_obj_set_height(ui_ImgButton9, 64);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_ImgButton10 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_201442241, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton10, 64);
    lv_obj_set_height(ui_ImgButton10, 64);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ImgButton10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ImgButton10, &ui_img_201442241, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ImgButton10, &ui_img_click_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton11 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_handshake_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton11, 64);
    lv_obj_set_height(ui_ImgButton11, 64);
    lv_obj_set_align(ui_ImgButton11, LV_ALIGN_CENTER);

    ui_ImgButton12 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cart_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton12, 64);
    lv_obj_set_height(ui_ImgButton12, 64);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_CENTER);

    ui_ImgButton13 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_profit_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton13, 64);
    lv_obj_set_height(ui_ImgButton13, 64);
    lv_obj_set_align(ui_ImgButton13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ImgButton13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton14 = lv_imgbtn_create(ui_Tablea1);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_delete_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_click_png, NULL);
    lv_obj_set_width(ui_ImgButton14, 64);
    lv_obj_set_height(ui_ImgButton14, 64);
    lv_obj_set_align(ui_ImgButton14, LV_ALIGN_CENTER);

    ui_ScreenSleepMode1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ScreenSleepMode1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1973681197, NULL);
    lv_obj_set_width(ui_ScreenSleepMode1, 24);
    lv_obj_set_height(ui_ScreenSleepMode1, 24);
    lv_obj_set_x(ui_ScreenSleepMode1, 141);
    lv_obj_set_y(ui_ScreenSleepMode1, -101);
    lv_obj_set_align(ui_ScreenSleepMode1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenSleepMode1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    ui_LabelClock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClock, 81);
    lv_obj_set_y(ui_LabelClock, -102);
    lv_obj_set_align(ui_LabelClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClock, "");
    lv_obj_add_flag(ui_LabelClock, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_LabelClock, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderWifi = lv_slider_create(ui_Screen1);
    lv_slider_set_mode(ui_SliderWifi, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_SliderWifi, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWifi) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderWifi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWifi, 32);
    lv_obj_set_height(ui_SliderWifi, 33);
    lv_obj_set_x(ui_SliderWifi, -107);
    lv_obj_set_y(ui_SliderWifi, -102);
    lv_obj_set_align(ui_SliderWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderWifi, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_bg_color(ui_SliderWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderWifi, &ui_img_8670999, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderWifi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifi, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderWifi, &ui_img_wifi_4_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderWifi, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifi, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Notificacoes = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Notificacoes, 320);
    lv_obj_set_height(ui_Notificacoes, 36);
    lv_obj_set_x(ui_Notificacoes, 0);
    lv_obj_set_y(ui_Notificacoes, 95);
    lv_obj_set_align(ui_Notificacoes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Notificacoes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Notificacoes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Notificacoes);
    lv_img_set_src(ui_Image1, &ui_img_462869052);
    lv_obj_set_width(ui_Image1, 32);
    lv_obj_set_height(ui_Image1, 32);
    lv_obj_set_x(ui_Image1, -142);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NotificationNumber = lv_label_create(ui_Notificacoes);
    lv_obj_set_width(ui_NotificationNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotificationNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotificationNumber, -113);
    lv_obj_set_y(ui_NotificationNumber, 0);
    lv_obj_set_align(ui_NotificationNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NotificationNumber, "0");
    lv_obj_set_style_text_color(ui_NotificationNumber, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NotificationNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NotificationNumber, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Notificacoes);
    lv_obj_set_width(ui_Button1, 250);
    lv_obj_set_height(ui_Button1, 36);
    lv_obj_set_x(ui_Button1, 27);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton11, ui_event_ImgButton11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton13, ui_event_ImgButton13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton14, ui_event_ImgButton14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSleepMode1, ui_event_ScreenSleepMode1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ImgButton1 = NULL;
    ui_Panel2 = NULL;
    ui_Button3 = NULL;
    ui_Panel1 = NULL;
    ui_Label1 = NULL;
    ui_Panel8 = NULL;
    ui_Label4 = NULL;
    ui_Switch1 = NULL;
    ui_Panel9 = NULL;
    ui_Label6 = NULL;
    ui_Switch2 = NULL;
    ui_Panel10 = NULL;
    ui_Label7 = NULL;
    ui_Switch3 = NULL;
    ui_Panel11 = NULL;
    ui_Label8 = NULL;
    ui_Switch4 = NULL;
    ui_Panel12 = NULL;
    ui_Label9 = NULL;
    ui_Switch5 = NULL;
    ui_Panel13 = NULL;
    ui_Label10 = NULL;
    ui_Switch6 = NULL;
    ui_Panel14 = NULL;
    ui_Label11 = NULL;
    ui_SwitchTheme1 = NULL;
    ui_Tablea1 = NULL;
    ui_ImgButton9 = NULL;
    ui_ImgButton10 = NULL;
    ui_ImgButton11 = NULL;
    ui_ImgButton12 = NULL;
    ui_ImgButton13 = NULL;
    ui_ImgButton14 = NULL;
    ui_ScreenSleepMode1 = NULL;
    ui_LabelClock = NULL;
    ui_SliderWifi = NULL;
    ui_Notificacoes = NULL;
    ui_Image1 = NULL;
    ui_NotificationNumber = NULL;
    ui_Button1 = NULL;

}
