// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Shopee = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_LabelSalesShopee = NULL;
lv_obj_t * ui_RETURNHOME9 = NULL;
// event funtions

// build funtions

void ui_Shopee_screen_init(void)
{
    ui_Shopee = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Shopee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Shopee, lv_color_hex(0xFF8600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Shopee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Shopee);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -2);
    lv_obj_set_y(ui_Label12, -105);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Shopee Sell's");

    ui_LabelSalesShopee = lv_label_create(ui_Shopee);
    lv_obj_set_width(ui_LabelSalesShopee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalesShopee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSalesShopee, -6);
    lv_obj_set_y(ui_LabelSalesShopee, -81);
    lv_obj_set_align(ui_LabelSalesShopee, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalesShopee, "--");

    ui_RETURNHOME9 = ui_RETURNHOME_create(ui_Shopee);
    lv_obj_set_x(ui_RETURNHOME9, -139);
    lv_obj_set_y(ui_RETURNHOME9, -99);

}

void ui_Shopee_screen_destroy(void)
{
    if(ui_Shopee) lv_obj_del(ui_Shopee);

    // NULL screen variables
    ui_Shopee = NULL;
    ui_Label12 = NULL;
    ui_LabelSalesShopee = NULL;
    ui_RETURNHOME9 = NULL;

}
