// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENSLEEPMODE_H
#define UI_SCREENSLEEPMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSleepMode
extern void ui_ScreenSleepMode_screen_init(void);
extern void ui_ScreenSleepMode_screen_destroy(void);
extern lv_obj_t * ui_ScreenSleepMode;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

