// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SHOPEE_H
#define UI_SHOPEE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Shopee
extern void ui_Shopee_screen_init(void);
extern void ui_Shopee_screen_destroy(void);
extern lv_obj_t * ui_Shopee;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelSalesShopee;
extern lv_obj_t * ui_RETURNHOME9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

