// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TELAPARAENVIAR_H
#define UI_TELAPARAENVIAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TelaParaEnviar
extern void ui_TelaParaEnviar_screen_init(void);
extern void ui_TelaParaEnviar_screen_destroy(void);
extern lv_obj_t * ui_TelaParaEnviar;
extern lv_obj_t * ui_RETURNHOME1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelToShip;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

