// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TELANOTIFICACOES_H
#define UI_TELANOTIFICACOES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TelaNotificacoes
extern void ui_TelaNotificacoes_screen_init(void);
extern void ui_TelaNotificacoes_screen_destroy(void);
extern lv_obj_t * ui_TelaNotificacoes;
extern lv_obj_t * ui_BtnClearNotifications;
extern lv_obj_t * ui_PanelNotif0;
extern lv_obj_t * ui_LabelNotif0;
extern lv_obj_t * ui_PanelNotif1;
extern lv_obj_t * ui_LabelNotif1;
extern lv_obj_t * ui_PanelNotif2;
extern lv_obj_t * ui_LabelNotif2;
extern lv_obj_t * ui_PanelNotif3;
extern lv_obj_t * ui_LabelNotif3;
extern lv_obj_t * ui_PanelNotif4;
extern lv_obj_t * ui_LabelNotif4;
extern lv_obj_t * ui_PanelNotif5;
extern lv_obj_t * ui_LabelNotif5;
extern lv_obj_t * ui_PanelNotif6;
extern lv_obj_t * ui_LabelNotif6;
extern lv_obj_t * ui_PanelNotif7;
extern lv_obj_t * ui_LabelNotif7;
extern lv_obj_t * ui_PanelNotif8;
extern lv_obj_t * ui_LabelNotif8;
extern lv_obj_t * ui_RETURNHOME2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

