// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TELAPARARETIRADA_H
#define UI_TELAPARARETIRADA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TelaParaRetirada
extern void ui_TelaParaRetirada_screen_init(void);
extern void ui_TelaParaRetirada_screen_destroy(void);
extern lv_obj_t * ui_TelaParaRetirada;
extern lv_obj_t * ui_RETURNHOME3;
extern lv_obj_t * ui_LabelToRetrieve;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

