// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TelaNotificacoes = NULL;
lv_obj_t * ui_BtnClearNotifications = NULL;
lv_obj_t * ui_PanelNotif0 = NULL;
lv_obj_t * ui_LabelNotif0 = NULL;
lv_obj_t * ui_PanelNotif1 = NULL;
lv_obj_t * ui_LabelNotif1 = NULL;
lv_obj_t * ui_PanelNotif2 = NULL;
lv_obj_t * ui_LabelNotif2 = NULL;
lv_obj_t * ui_PanelNotif3 = NULL;
lv_obj_t * ui_LabelNotif3 = NULL;
lv_obj_t * ui_PanelNotif4 = NULL;
lv_obj_t * ui_LabelNotif4 = NULL;
lv_obj_t * ui_PanelNotif5 = NULL;
lv_obj_t * ui_LabelNotif5 = NULL;
lv_obj_t * ui_PanelNotif6 = NULL;
lv_obj_t * ui_LabelNotif6 = NULL;
lv_obj_t * ui_PanelNotif7 = NULL;
lv_obj_t * ui_LabelNotif7 = NULL;
lv_obj_t * ui_PanelNotif8 = NULL;
lv_obj_t * ui_LabelNotif8 = NULL;
lv_obj_t * ui_RETURNHOME2 = NULL;
// event funtions

// build funtions

void ui_TelaNotificacoes_screen_init(void)
{
    ui_TelaNotificacoes = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_TelaNotificacoes, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TelaNotificacoes, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_TelaNotificacoes, &ui_img_wdaswdasdaw_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnClearNotifications = lv_btn_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_BtnClearNotifications, 32);
    lv_obj_set_height(ui_BtnClearNotifications, 32);
    lv_obj_set_x(ui_BtnClearNotifications, 137);
    lv_obj_set_y(ui_BtnClearNotifications, -98);
    lv_obj_set_align(ui_BtnClearNotifications, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnClearNotifications, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnClearNotifications, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnClearNotifications, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnClearNotifications, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnClearNotifications, &ui_img_close_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotif0 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif0, 200);
    lv_obj_set_height(ui_PanelNotif0, 36);
    lv_obj_set_x(ui_PanelNotif0, 237);
    lv_obj_set_y(ui_PanelNotif0, 91);
    lv_obj_set_align(ui_PanelNotif0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif0, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif0, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif0 = lv_label_create(ui_PanelNotif0);
    lv_obj_set_width(ui_LabelNotif0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif0, LV_ALIGN_CENTER);

    ui_PanelNotif1 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif1, 200);
    lv_obj_set_height(ui_PanelNotif1, 36);
    lv_obj_set_x(ui_PanelNotif1, 237);
    lv_obj_set_y(ui_PanelNotif1, 91);
    lv_obj_set_align(ui_PanelNotif1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif1, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif1 = lv_label_create(ui_PanelNotif1);
    lv_obj_set_width(ui_LabelNotif1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif1, LV_ALIGN_CENTER);

    ui_PanelNotif2 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif2, 200);
    lv_obj_set_height(ui_PanelNotif2, 36);
    lv_obj_set_x(ui_PanelNotif2, 237);
    lv_obj_set_y(ui_PanelNotif2, 91);
    lv_obj_set_align(ui_PanelNotif2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif2, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif2 = lv_label_create(ui_PanelNotif2);
    lv_obj_set_width(ui_LabelNotif2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif2, LV_ALIGN_CENTER);

    ui_PanelNotif3 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif3, 200);
    lv_obj_set_height(ui_PanelNotif3, 36);
    lv_obj_set_x(ui_PanelNotif3, 237);
    lv_obj_set_y(ui_PanelNotif3, 91);
    lv_obj_set_align(ui_PanelNotif3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif3, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif3 = lv_label_create(ui_PanelNotif3);
    lv_obj_set_width(ui_LabelNotif3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif3, LV_ALIGN_CENTER);

    ui_PanelNotif4 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif4, 200);
    lv_obj_set_height(ui_PanelNotif4, 36);
    lv_obj_set_x(ui_PanelNotif4, 237);
    lv_obj_set_y(ui_PanelNotif4, 91);
    lv_obj_set_align(ui_PanelNotif4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif4, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif4, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif4 = lv_label_create(ui_PanelNotif4);
    lv_obj_set_width(ui_LabelNotif4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif4, LV_ALIGN_CENTER);

    ui_PanelNotif5 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif5, 200);
    lv_obj_set_height(ui_PanelNotif5, 36);
    lv_obj_set_x(ui_PanelNotif5, 237);
    lv_obj_set_y(ui_PanelNotif5, 91);
    lv_obj_set_align(ui_PanelNotif5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif5, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif5, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif5 = lv_label_create(ui_PanelNotif5);
    lv_obj_set_width(ui_LabelNotif5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif5, LV_ALIGN_CENTER);

    ui_PanelNotif6 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif6, 200);
    lv_obj_set_height(ui_PanelNotif6, 36);
    lv_obj_set_x(ui_PanelNotif6, 237);
    lv_obj_set_y(ui_PanelNotif6, 91);
    lv_obj_set_align(ui_PanelNotif6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif6, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif6, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif6 = lv_label_create(ui_PanelNotif6);
    lv_obj_set_width(ui_LabelNotif6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif6, LV_ALIGN_CENTER);

    ui_PanelNotif7 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif7, 200);
    lv_obj_set_height(ui_PanelNotif7, 36);
    lv_obj_set_x(ui_PanelNotif7, 237);
    lv_obj_set_y(ui_PanelNotif7, 91);
    lv_obj_set_align(ui_PanelNotif7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif7, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif7, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif7 = lv_label_create(ui_PanelNotif7);
    lv_obj_set_width(ui_LabelNotif7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif7, LV_ALIGN_CENTER);

    ui_PanelNotif8 = lv_obj_create(ui_TelaNotificacoes);
    lv_obj_set_width(ui_PanelNotif8, 200);
    lv_obj_set_height(ui_PanelNotif8, 36);
    lv_obj_set_x(ui_PanelNotif8, 237);
    lv_obj_set_y(ui_PanelNotif8, 91);
    lv_obj_set_align(ui_PanelNotif8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNotif8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNotif8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotif8, lv_color_hex(0x0009FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotif8, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotif8 = lv_label_create(ui_PanelNotif8);
    lv_obj_set_width(ui_LabelNotif8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotif8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotif8, LV_ALIGN_CENTER);

    ui_RETURNHOME2 = ui_RETURNHOME_create(ui_TelaNotificacoes);
    lv_imgbtn_set_src(ui_RETURNHOME2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1275314971, NULL);
    lv_obj_set_x(ui_RETURNHOME2, -139);
    lv_obj_set_y(ui_RETURNHOME2, -99);

}

void ui_TelaNotificacoes_screen_destroy(void)
{
    if(ui_TelaNotificacoes) lv_obj_del(ui_TelaNotificacoes);

    // NULL screen variables
    ui_TelaNotificacoes = NULL;
    ui_BtnClearNotifications = NULL;
    ui_PanelNotif0 = NULL;
    ui_LabelNotif0 = NULL;
    ui_PanelNotif1 = NULL;
    ui_LabelNotif1 = NULL;
    ui_PanelNotif2 = NULL;
    ui_LabelNotif2 = NULL;
    ui_PanelNotif3 = NULL;
    ui_LabelNotif3 = NULL;
    ui_PanelNotif4 = NULL;
    ui_LabelNotif4 = NULL;
    ui_PanelNotif5 = NULL;
    ui_LabelNotif5 = NULL;
    ui_PanelNotif6 = NULL;
    ui_LabelNotif6 = NULL;
    ui_PanelNotif7 = NULL;
    ui_LabelNotif7 = NULL;
    ui_PanelNotif8 = NULL;
    ui_LabelNotif8 = NULL;
    ui_RETURNHOME2 = NULL;

}
