// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TELAPARAIMPRIMIR_H
#define UI_TELAPARAIMPRIMIR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TelaParaImprimir
extern void ui_TelaParaImprimir_screen_init(void);
extern void ui_TelaParaImprimir_screen_destroy(void);
extern lv_obj_t * ui_TelaParaImprimir;
extern lv_obj_t * ui_RETURNHOME4;
extern lv_obj_t * ui_LabelToPrint;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

