// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TelaParaEnviar = NULL;
lv_obj_t * ui_RETURNHOME1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LabelToShip = NULL;
// event funtions

// build funtions

void ui_TelaParaEnviar_screen_init(void)
{
    ui_TelaParaEnviar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TelaParaEnviar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TelaParaEnviar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TelaParaEnviar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME1 = ui_RETURNHOME_create(ui_TelaParaEnviar);
    lv_obj_set_x(ui_RETURNHOME1, -139);
    lv_obj_set_y(ui_RETURNHOME1, -99);

    ui_Label2 = lv_label_create(ui_TelaParaEnviar);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -4);
    lv_obj_set_y(ui_Label2, -103);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "To Send");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelToShip = lv_label_create(ui_TelaParaEnviar);
    lv_obj_set_width(ui_LabelToShip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelToShip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelToShip, -6);
    lv_obj_set_y(ui_LabelToShip, -83);
    lv_obj_set_align(ui_LabelToShip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelToShip, "--");
    lv_obj_set_style_text_color(ui_LabelToShip, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelToShip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TelaParaEnviar_screen_destroy(void)
{
    if(ui_TelaParaEnviar) lv_obj_del(ui_TelaParaEnviar);

    // NULL screen variables
    ui_TelaParaEnviar = NULL;
    ui_RETURNHOME1 = NULL;
    ui_Label2 = NULL;
    ui_LabelToShip = NULL;

}
