// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TelaParaRetirada = NULL;
lv_obj_t * ui_RETURNHOME3 = NULL;
lv_obj_t * ui_LabelToRetrieve = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions

// build funtions

void ui_TelaParaRetirada_screen_init(void)
{
    ui_TelaParaRetirada = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TelaParaRetirada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TelaParaRetirada, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TelaParaRetirada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME3 = ui_RETURNHOME_create(ui_TelaParaRetirada);
    lv_obj_set_x(ui_RETURNHOME3, -139);
    lv_obj_set_y(ui_RETURNHOME3, -99);

    ui_LabelToRetrieve = lv_label_create(ui_TelaParaRetirada);
    lv_obj_set_width(ui_LabelToRetrieve, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelToRetrieve, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelToRetrieve, -6);
    lv_obj_set_y(ui_LabelToRetrieve, -83);
    lv_obj_set_align(ui_LabelToRetrieve, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelToRetrieve, "--");
    lv_obj_set_style_text_color(ui_LabelToRetrieve, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelToRetrieve, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TelaParaRetirada);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -4);
    lv_obj_set_y(ui_Label3, -103);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "To Retrieve:");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TelaParaRetirada_screen_destroy(void)
{
    if(ui_TelaParaRetirada) lv_obj_del(ui_TelaParaRetirada);

    // NULL screen variables
    ui_TelaParaRetirada = NULL;
    ui_RETURNHOME3 = NULL;
    ui_LabelToRetrieve = NULL;
    ui_Label3 = NULL;

}
