// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_TelaParaImprimir = NULL;
lv_obj_t * ui_RETURNHOME4 = NULL;
lv_obj_t * ui_LabelToPrint = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_TelaParaImprimir_screen_init(void)
{
    ui_TelaParaImprimir = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TelaParaImprimir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TelaParaImprimir, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TelaParaImprimir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURNHOME4 = ui_RETURNHOME_create(ui_TelaParaImprimir);
    lv_obj_set_x(ui_RETURNHOME4, -139);
    lv_obj_set_y(ui_RETURNHOME4, -99);

    ui_LabelToPrint = lv_label_create(ui_TelaParaImprimir);
    lv_obj_set_width(ui_LabelToPrint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelToPrint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelToPrint, -6);
    lv_obj_set_y(ui_LabelToPrint, -83);
    lv_obj_set_align(ui_LabelToPrint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelToPrint, "--");
    lv_obj_set_style_text_color(ui_LabelToPrint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelToPrint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TelaParaImprimir);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -4);
    lv_obj_set_y(ui_Label5, -103);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "To Print:");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TelaParaImprimir_screen_destroy(void)
{
    if(ui_TelaParaImprimir) lv_obj_del(ui_TelaParaImprimir);

    // NULL screen variables
    ui_TelaParaImprimir = NULL;
    ui_RETURNHOME4 = NULL;
    ui_LabelToPrint = NULL;
    ui_Label5 = NULL;

}
